name: Cordova Android builds

on:
  push:
    branches:
      - cordova_builds
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: pull amplify environment
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_command: pull
        amplify_env: kikelia
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
    - name: Production Build
      run: npm run build
      env:
        REACT_APP_DEMO_MODE: false
        REACT_APP_OFFLINE_ONLY: false
        REACT_APP_POPULATE_FAKE_DATA: false
        CI: false
        GENERATE_SOURCEMAP: false
    - name: NPM test
      run: npm test -- --silent
    - name: Use duckbytes/setup-cordova
      uses: duckbytes/setup-cordova@0.0.4
      with:
        exec: |
          cd cordova
          ln -s ../build/ www
          cordova platform add android && \
          cordova build --no-telemetry && \
          cp "$(find . -name '*.apk')" .
