on:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
